In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!mkdir -p '/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file'
%cd '/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file'

Mounted at /content/drive
/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file

In [ ]:
# install flair library
!pip install flair
#!conda install pytorch torchvision torchaudio cpuonly -c pytorch

Collecting flair
  Downloading flair-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting boto3>=1.20.27 (from flair)
  Downloading boto3-1.35.71-py3-none-any.whl.metadata (6.7 kB)
Collecting conllu<5.0.0,>=4.0 (from flair)
  Downloading conllu-4.5.3-py2.py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: deprecated>=1.2.13 in /usr/local/lib/python3.10/dist-packages (from flair) (1.2.15)
Collecting ftfy>=6.1.0 (from flair)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: gdown>=4.4.0 in /usr/local/lib/python3.10/dist-packages (from flair) (5.2.0)
Requirement already satisfied: huggingface-hub>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from flair) (0.26.2)
Collecting langdetect>=1.0.9 (from flair)
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 43.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: lxml>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from flair) (5.3.0)
Requirement already satisfied: matplotlib>=2.2.3 in /usr/local/lib/python3.10/dist-packages (from flair) (3.8.0)
Requirement already satisfied: more-itertools>=8.13.0 in /usr/local/lib/python3.10/dist-packages (from flair) (10.5.0)
Collecting mpld3>=0.3 (from flair)
  Downloading mpld3-0.5.10-py3-none-any.whl.metadata (5.1 kB)
Collecting pptree>=3.1 (from flair)
  Downloading pptree-3.1.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from flair) (2.8.2)
Collecting pytorch-revgrad>=0.2.0 (from flair)
  Downloading pytorch_revgrad-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.10/dist-packages (from flair) (2024.9.11)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from flair) (1.5.2)
Collecting segtok>=1.5.11 (from flair)
  Downloading segtok-1.5.11-py3-none-any.whl.metadata (9.0 kB)
Collecting sqlitedict>=2.0.0 (from flair)
  Downloading sqlitedict-2.1.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tabulate>=0.8.10 in /usr/local/lib/python3.10/dist-packages (from flair) (0.9.0)
Requirement already satisfied: torch!=1.8,>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from flair) (2.5.1+cu121)
Requirement already satisfied: tqdm>=4.63.0 in /usr/local/lib/python3.10/dist-packages (from flair) (4.66.6)
Collecting transformer-smaller-training-vocab>=0.2.3 (from flair)
  Downloading transformer_smaller_training_vocab-0.4.0-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: transformers<5.0.0,>=4.18.0 in /usr/local/lib/python3.10/dist-packages (from transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (4.46.2)
Collecting wikipedia-api>=0.5.7 (from flair)
  Downloading wikipedia_api-0.7.1.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting semver<4.0.0,>=3.0.0 (from flair)
  Downloading semver-3.0.2-py3-none-any.whl.metadata (5.0 kB)
Collecting bioc<3.0.0,>=2.0.0 (from flair)
  Downloading bioc-2.1-py3-none-any.whl.metadata (4.6 kB)
Collecting jsonlines>=1.2.0 (from bioc<3.0.0,>=2.0.0->flair)
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting intervaltree (from bioc<3.0.0,>=2.0.0->flair)
  Downloading intervaltree-3.1.0.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting docopt (from bioc<3.0.0,>=2.0.0->flair)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting botocore<1.36.0,>=1.35.71 (from boto3>=1.20.27->flair)
  Downloading botocore-1.35.71-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.20.27->flair)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.11.0,>=0.10.0 (from boto3>=1.20.27->flair)
  Downloading s3transfer-0.10.4-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from deprecated>=1.2.13->flair) (1.16.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from ftfy>=6.1.0->flair) (0.2.13)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown>=4.4.0->flair) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown>=4.4.0->flair) (3.16.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown>=4.4.0->flair) (2.32.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.10.0->flair) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.10.0->flair) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.10.0->flair) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.10.0->flair) (4.12.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect>=1.0.9->flair) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.2.3->flair) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.2.3->flair) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.2.3->flair) (4.55.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.2.3->flair) (1.4.7)
Requirement already satisfied: numpy<2,>=1.21 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.2.3->flair) (1.26.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.2.3->flair) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.2.3->flair) (3.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from mpld3>=0.3->flair) (3.1.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.2->flair) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.2->flair) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.2->flair) (3.5.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch!=1.8,>=1.5.0->flair) (3.4.2)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch!=1.8,>=1.5.0->flair) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch!=1.8,>=1.5.0->flair) (1.3.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.18.0->transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.18.0->transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (0.20.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (4.25.5)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.10/dist-packages (from transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (0.2.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.10/dist-packages (from botocore<1.36.0,>=1.35.71->boto3>=1.20.27->flair) (2.2.3)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonlines>=1.2.0->bioc<3.0.0,>=2.0.0->flair) (24.2.0)
Requirement already satisfied: accelerate>=0.26.0 in /usr/local/lib/python3.10/dist-packages (from transformers[sentencepiece,torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair) (1.1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown>=4.4.0->flair) (2.6)
Collecting sortedcontainers<3.0,>=2.0 (from intervaltree->bioc<3.0.0,>=2.0.0->flair)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->mpld3>=0.3->flair) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (2024.8.30)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=4.4.0->flair) (1.7.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.26.0->transformers[sentencepiece,torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair) (5.9.5)
Downloading flair-0.14.0-py3-none-any.whl (776 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.5/776.5 kB 57.3 MB/s eta 0:00:00
Downloading bioc-2.1-py3-none-any.whl (33 kB)
Downloading boto3-1.35.71-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.2/139.2 kB 14.8 MB/s eta 0:00:00
Downloading conllu-4.5.3-py2.py3-none-any.whl (16 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 4.2 MB/s eta 0:00:00
Downloading mpld3-0.5.10-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.6/202.6 kB 21.7 MB/s eta 0:00:00
Downloading pytorch_revgrad-0.2.0-py3-none-any.whl (4.6 kB)
Downloading segtok-1.5.11-py3-none-any.whl (24 kB)
Downloading semver-3.0.2-py3-none-any.whl (17 kB)
Downloading transformer_smaller_training_vocab-0.4.0-py3-none-any.whl (14 kB)
Downloading botocore-1.35.71-py3-none-any.whl (13.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 111.5 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Downloading s3transfer-0.10.4-py3-none-any.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.2/83.2 kB 8.9 MB/s eta 0:00:00
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: langdetect, pptree, sqlitedict, wikipedia-api, docopt, intervaltree
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993222 sha256=e9a0b2cd127361c03527c87176d77b0a3a1c33eb7f62e322162c7575850d8dba
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
  Building wheel for pptree (setup.py) ... done
  Created wheel for pptree: filename=pptree-3.1-py3-none-any.whl size=4608 sha256=581fb17db60c38cf1984171245fe669bc14ba0804c2cb8cf7e71e554474cc937
  Stored in directory: /root/.cache/pip/wheels/9f/b6/0e/6f26eb9e6eb53ff2107a7888d72b5a6a597593956113037828
  Building wheel for sqlitedict (setup.py) ... done
  Created wheel for sqlitedict: filename=sqlitedict-2.1.0-py3-none-any.whl size=16864 sha256=49844676c41e7078d9959aaea6000402ba0fbebd2561e078708e5834917bd7f0
  Stored in directory: /root/.cache/pip/wheels/79/d6/e7/304e0e6cb2221022c26d8161f7c23cd4f259a9e41e8bbcfabd
  Building wheel for wikipedia-api (setup.py) ... done
  Created wheel for wikipedia-api: filename=Wikipedia_API-0.7.1-py3-none-any.whl size=14346 sha256=722df77c64f54f7674ffc4759ee7407bb48b803a8969a882b1cbf13025e10bd5
  Stored in directory: /root/.cache/pip/wheels/4c/96/18/b9201cc3e8b47b02b510460210cfd832ccf10c0c4dd0522962
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=f9c9b134637fdec821583f9881f977d72cdf7801a38efd97cadfa97607ef4c41
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
  Building wheel for intervaltree (setup.py) ... done
  Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26097 sha256=7374e9e1e2910a1f8b95700503ef2a3280c44b4682c21c19362dd5890a90a0cd
  Stored in directory: /root/.cache/pip/wheels/fa/80/8c/43488a924a046b733b64de3fac99252674c892a4c3801c0a61
Successfully built langdetect pptree sqlitedict wikipedia-api docopt intervaltree
Installing collected packages: sqlitedict, sortedcontainers, pptree, docopt, semver, segtok, langdetect, jsonlines, jmespath, intervaltree, ftfy, conllu, wikipedia-api, botocore, bioc, s3transfer, pytorch-revgrad, mpld3, boto3, transformer-smaller-training-vocab, flair
Successfully installed bioc-2.1 boto3-1.35.71 botocore-1.35.71 conllu-4.5.3 docopt-0.6.2 flair-0.14.0 ftfy-6.3.1 intervaltree-3.1.0 jmespath-1.0.1 jsonlines-4.0.0 langdetect-1.0.9 mpld3-0.5.10 pptree-3.1 pytorch-revgrad-0.2.0 s3transfer-0.10.4 segtok-1.5.11 semver-3.0.2 sortedcontainers-2.4.0 sqlitedict-2.1.0 transformer-smaller-training-vocab-0.4.0 wikipedia-api-0.7.1

In [ ]:
# Load NLP Pkg
import flair
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', None)

In [ ]:
# Methods/Attrib
dir(flair)

['Path',
 '__all__',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_arrow',
 'cache_root',
 'class_utils',
 'data',
 'datasets',
 'device',
 'device_id',
 'embeddings',
 'file_utils',
 'hf_set_seed',
 'logger',
 'logging',
 'models',
 'nn',
 'optim',
 'os',
 'samplers',
 'set_proxies',
 'set_seed',
 'splitter',
 'tokenization',
 'torch',
 'trainers',
 'training_utils',
 'visual']

In [ ]:
# read the dataset
df = pd.read_csv(r"/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/merged_text_based_reviews.csv")

In [ ]:
# show the first 5rows
df.head()

,Company Name,Place ID,Author,Rating,Review Text
0,1 Click Heating and Cooling,ChIJ3YAdKC0tK4gR-C65HnnGxZg,Glen Brothers,5.0,"The guys showed up in full force! Installers and electricians ready to go. As a small business owner, I appreciate the coordination in doing such a job in a timely manner. 1st thing I noticed, was the relatively young age of the crew, which was a pleasant surprise! I know all too well how hard it is to recruit young workers these days. The crew was very knowledgeable in their field and worked together flawlessly. Adrianna and Mike at 1-click were great to deal with, and made the transition from oil to electric go very smoothly. No money up front, as a lot of people thought. If you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. If you are thinking of making the transition from oil to electric or looking for other options… give 1-click a call and speak to Mike or Adrianna!"
1,1 Click Heating and Cooling,ChIJ3YAdKC0tK4gR-C65HnnGxZg,Stacey,5.0,"Working with 1 Click to set up our ductless heat & air conditioning in our home in Nova Scotia has been seamlessly, worry free. Our rep George was very transparent and knowledgeable. He was and is always available to answer any questions or guidance. The installers are some of most respectful workers I’ve ever had in my home, their workmanship was impeccable! Extremely neat and professional. We would definitely recommend George and 1 Click based on our experience with them"
2,1 Click Heating and Cooling,ChIJ3YAdKC0tK4gR-C65HnnGxZg,Dee Brake,5.0,"We knew we wanted a heat pump, but we didn't know what type was best. Originally, we considered a ducted unit, but in the end, we chose a multi split. We have 3 heads to best service our home. Kingsley was very patient and helpful with us and our indecisiveness. He helped us choose the right unit for us. The installation went smoothly. The team was efficient and tidy. The units look great. Kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. They were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. Kingsley even helped us with the application and financing websites. I would highly recommend this service to friends. I'm now enjoying the comfort of multi zone climate control."
3,1 Click Heating and Cooling,ChIJ3YAdKC0tK4gR-C65HnnGxZg,Melanie Gillam,5.0,"It was an absolute pleasure working with this company, especially Adrianna, Dylan and George. They were available and extremely helpful every step of the way, even though I know I must have drove them crazy at times. I would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered.\nMelanie,\nPort aux Basques, NL"
4,1 Click Heating and Cooling,ChIJ3YAdKC0tK4gR-C65HnnGxZg,Tony Parsons,5.0,"On Labour Day Weekend I filled out a basic request for a quote and by noon on the Tuesday following the long weekend Kage had reached out and not only offered a written quote but financing options for the modest amount not covered by Rebates and the information required to complete the Rebate Application.\n\nWhile waiting for Rebate Approval, they touched base weekly and one day after confirmation, co-ordinated Electrical and HVAC Companies (from two different areas of the Province) and an Installation date. The contractors showed up on-time and were professional, respectful, knowledgable and surprisingly young.\n\nBy mid afternoon, a heat pump, and three heads had been neatly installed and working; and the oil tank removed. From an office in Toronto to the rural town of Sandy Cove, Newfoundland; 1Click and its sub-contractors made the whole experience smooth and hassel free. Kudos all round."

make sure if there are any missing values.

In [ ]:
df.isna().sum()

Company Name        0
Place ID            0
Author              6
Rating              6
Review Text     44433
dtype: int64

identify the missing values.

In [ ]:
drop_rows1 = df[df['Author'].isna()].index
drop_rows2 = df[df['Rating'].isna()].index
drop_rows3 = df[df['Review Text'].isna()].index

In [ ]:
print(drop_rows1)
print(drop_rows2)
print(drop_rows3)

Index([124972, 124983, 124991, 124995, 124999, 125012], dtype='int64')
Index([124972, 124983, 124991, 124995, 124999, 125012], dtype='int64')
Index([   140,    141,    142,    143,    144,    145,    146,    147,    148,
          149,
       ...
       139563, 139564, 139565, 139566, 139570, 139571, 139572, 139575, 139576,
       139579],
      dtype='int64', length=44433)

drop them.

In [ ]:
#df = df.drop(drop_rows1)
#df = df.drop(drop_rows2)
df = df.drop(drop_rows3)

reset the index.

In [ ]:
df = df.reset_index(drop=True)

make sure if no missing values after cleaning.

In [ ]:
df.isna().sum()

Company Name    0
Place ID        0
Author          6
Rating          6
Review Text     0
dtype: int64

In [ ]:
#df = df.drop(drop_rows1)

In [ ]:
# Check for value count
df['Author'].value_counts()

Author
Mike               31
Ryan               26
John               25
Alex               24
Chris              22
                   ..
Jill R              1
John a              1
Joshua Lomonaco     1
Victor Mijares      1
Mina Movahedi       1
Name: count, Length: 77667, dtype: int64

In [ ]:
df.columns

Index(['Company Name', 'Place ID', 'Author', 'Rating', 'Review Text'], dtype='object')

In [ ]:
df.to_csv("/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/merged_text_based_reviews_cleaned.csv")

# NER by Flair

In [ ]:
# import flair library for NER
from flair.data import Sentence
from flair.nn import Classifier
from flair.models import SequenceTagger
 #Load the model
tagger = SequenceTagger.load('ner')
sentence = Sentence('George Washington went to Washington.')
tagger.predict(sentence)

print(sentence.to_tagged_string())

for entity in sentence.get_spans('ner'):
    print(entity)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/419M [00:00<?, ?B/s]

2024-10-20 18:12:46,985 SequenceTagger predicts: Dictionary with 20 tags: <unk>, O, S-ORG, S-MISC, B-PER, E-PER, S-LOC, B-ORG, E-ORG, I-PER, S-PER, B-MISC, I-MISC, E-MISC, I-ORG, B-LOC, E-LOC, I-LOC, <START>, <STOP>
Sentence[6]: "George Washington went to Washington." → ["George Washington"/PER, "Washington"/LOC]
Span[0:2]: "George Washington" → PER (0.9989)
Span[4:5]: "Washington" → LOC (0.9942)

In [ ]:
#function for NER
def apply_ner(text):
    sentence = Sentence(text)
    tagger.predict(sentence)
    entities = sentence.to_dict(tag_type='ner')['entities']
    return entities

In [ ]:
# change the data type to string in Review Text column
df['Review_Text'] = str(df['Review Text'])

In [ ]:
#apply NER to entire dataset
df['entities'] = df['Review Text'].apply(apply_ner)

#save the result
df.to_csv('/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/ner_result_flair.csv', index=False)

In [ ]:
# import pandas and ast
import pandas as pd
import ast  # convert to list

df1 = pd.read_csv('/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/ner_result_flair.csv')

In [ ]:
# function to clean the reviews (eliminate unnecessary words and change the sentence.)
def clean_review_text(text):
    text = text.replace('\n', ' ').replace('\r', '')
    text = text.strip()
    return text.lower()

# clean the sentences of column 'Review Text'. Apply the function of "clean_review_text".
df1['cleaned_review'] = df1['Review Text'].apply(clean_review_text)

# check the data frame
df1.head()

                  Company Name                     Place ID          Author  \
0  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg   Glen Brothers
1  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg          Stacey
2  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg       Dee Brake
3  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg  Melanie Gillam
4  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg    Tony Parsons

   Rating  \
0     5.0
1     5.0
2     5.0
3     5.0
4     5.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Review Text  \
0                                  The guys showed up in full force! Installers and electricians ready to go. As a small business owner, I appreciate the coordination in doing such a job in a timely manner. 1st thing I noticed, was the relatively young age of the crew, which was a pleasant surprise! I know all too well how hard it is to recruit young workers these days. The crew was very knowledgeable in their field and worked together flawlessly. Adrianna and Mike at 1-click were great to deal with, and made the transition from oil to electric go very smoothly. No money up front, as a lot of people thought. If you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. If you are thinking of making the transition from oil to electric or looking for other options… give 1-click a call and speak to Mike or Adrianna!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                 Working with 1 Click to set up our ductless heat & air conditioning in our home in Nova Scotia has been seamlessly, worry free. Our rep George was very transparent and knowledgeable. He was and is always available to answer any questions or guidance. The installers are some of most respectful workers I’ve ever had in my home, their workmanship was impeccable! Extremely neat and professional. We would definitely recommend George and 1 Click based on our experience with them
2                                                       We knew we wanted a heat pump, but we didn't know what type was best. Originally, we considered a ducted unit, but in the end, we chose a multi split. We have 3 heads to best service our home. Kingsley was very patient and helpful with us and our indecisiveness.  He helped us choose the right unit for us.  The installation went smoothly.  The team was efficient and tidy. The units look great. Kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. They were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. Kingsley even helped us with the application and financing websites. I would highly recommend this service to friends. I'm now enjoying the comfort of multi zone climate control.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 It was an absolute pleasure working with this company, especially Adrianna, Dylan and George. They were available and extremely helpful every step of the way, even though I know I must have drove them crazy at times. I would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered.\nMelanie,\nPort aux Basques, NL
4  On Labour Day Weekend I filled out a basic request for a quote and by noon on the Tuesday following the long weekend Kage had reached out and not only offered a written quote but financing options for the modest amount not covered by Rebates and the information required to complete the Rebate Application.\n\nWhile waiting for Rebate Approval, they touched base weekly and one day after confirmation, co-ordinated Electrical and HVAC Companies (from two different areas of the Province) and an Installation date.  The contractors showed up on-time and were professional, respectful, knowledgable and surprisingly young.\n\nBy mid afternoon, a heat pump, and three heads had been neatly installed and working; and the oil tank removed.  From an office in Toronto to the rural town of Sandy Cove, Newfoundland; 1Click and its sub-contractors made the whole experience smooth and hassel free.  Kudos all round.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Review_Text  \

In [ ]:
#convert str to list in the column of entities
df1['entities'] = df1['entities'].apply(lambda x: ast.literal_eval(x))

In [ ]:
# function for extracting builder name
def extract_buildername(entities):
    for entity in entities:
        if 'labels' in entity and entity['labels'][0]['value'] == 'PER':
            return entity['text']
    return None

In [ ]:
# function for extracting builder company
def extract_company(entities):
    companies = [entity['text'] for entity in entities if 'labels' in entity and entity['labels'][0]['value'] == 'ORG']
    return companies if companies else None

In [ ]:
# function for extracting builder location
def extract_location(entities):
    locations = [entity['text'] for entity in entities if 'labels' in entity and entity['labels'][0]['value'] == 'LOC']
    return locations if locations else None

In [ ]:
# function for extracting builder skills and characteristics
def extract_skills(entities, review_text):
    # extract the keyword of the specific characteristics
    skills = []
    for entity in entities:
        if 'labels' in entity and entity['labels'][0]['value'] == 'MISC':
            skills.append(entity['text'])

    # extract the specific keyword from review_text
    if "three-story" in review_text.lower():
        skills.append("three-story building")
    if "two-story" in review_text.lower():
        skills.append("two-story building")
    if "one-story" in review_text.lower():
        skills.append("one-story building")
    if "garage" in review_text.lower():
        skills.append("garage construction")
    if "basement" in review_text.lower():
        skills.append("basement construction")
    if "pool" in review_text.lower():
        skills.append("pool construction")
    if "garden" in review_text.lower():
        skills.append("garden construction")
    if "roof" in review_text.lower():
        skills.append("roof construction")
    if "elevator" in review_text.lower():
        skills.append("elevator construction")
    if "fireplace" in review_text.lower():
        skills.append("fireplace construction")
    if "security" in review_text.lower():
        skills.append("security construction")
    if "laundry" in review_text.lower():
        skills.append("laundry construction")
    if "storage" in review_text.lower():
        skills.append("storage construction")
    if "heating" in review_text.lower():
        skills.append("heating construction")
    if "cooling" in review_text.lower():
        skills.append("cooling construction")
    if "air conditioning" in review_text.lower():
        skills.append("air conditioning construction")
    if "water heater" in review_text.lower():
        skills.append("water heater construction")
    if "solar panel" in review_text.lower():
        skills.append("solar panel construction")
    if "panoramic view" in review_text.lower():
        skills.append("panoramic view construction")
    if "outdoor space" in review_text.lower():
        skills.append("outdoor space construction")
    if "balcony" in review_text.lower():
        skills.append("balcony construction")
    if "designable" in review_text.lower():
        skills.append("designable construction")
    if "interior design" in review_text.lower():
        skills.append("interior design construction")
    if "exterior design" in review_text.lower():
        skills.append("exterior design construction")
    if "renovation" in review_text.lower():
        skills.append("renovation construction")
    if "simple" in review_text.lower():
        skills.append("simple construction")
    if "sustainable" in review_text.lower():
        skills.append("sustainable construction")
    if "durable" in review_text.lower():
        skills.append("durable construction")

    return skills if skills else None

In [ ]:
# add each columns with new data
df1['builder_names'] = df1['entities'].apply(extract_buildername)
df1['companies'] = df1['entities'].apply(extract_company)
df1['locations'] = df1['entities'].apply(extract_location)
df1['skills'] = df1.apply(lambda row: extract_skills(row['entities'], row['cleaned_review']), axis=1)

# show the result
print(df1[['cleaned_review', 'builder_names', 'companies', 'locations', 'skills']].head(30))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cleaned_review  \
0                                                                                                                                                                                                                                                                              the guys showed up in full force! installers and electricians ready to go. as a small business owner, i appreciate the coordination in doing such a job in a timely manner. 1st thing i noticed, was the relatively young age of the crew, which was a pleasant surprise! i know all too well how hard it is to recruit young workers these days. the crew was very knowledgeable in their field and worked together flawlessly. adrianna and mike at 1-click were great to deal with, and made the transition from oil to electric go very smoothly. no money up front, as a lot of people thought. if you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. if you are thinking of making the transition from oil to electric or looking for other options… give 1-click a call and speak to mike or adrianna!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             working with 1 click to set up our ductless heat & air conditioning in our home in nova scotia has been seamlessly, worry free. our rep george was very transparent and knowledgeable. he was and is always available to answer any questions or guidance. the installers are some of most respectful workers i’ve ever had in my home, their workmanship was impeccable! extremely neat and professional. we would definitely recommend george and 1 click based on our experience with them
2                                                                                                                                                                                                                                                                                                   we knew we wanted a heat pump, but we didn't know what type was best. originally, we considered a ducted unit, but in the end, we chose a multi split. we have 3 heads to best service our home. kingsley was very patient and helpful with us and our indecisiveness.  he helped us choose the right unit for us.  the installation went smoothly.  the team was efficient and tidy. the units look great. kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. they were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. kingsley even helped us with the application and financing websites. i would highly recommend this service to friends. i'm now enjoying the comfort of multi zone climate control.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               it was an absolute pleasure working with this company, especially adrianna, dylan and george. they were available and extremely helpful every step of the way, even though i know i must have drove them crazy at times. i would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered. melanie, port aux basques, nl
4                                                                                                                                                                                                                                                  on labour day weekend i filled out a basic request for a quote and by noon on the tuesday following the long weekend kage had reached out and not only offered a written quote but financing options for the modest amount not covered by rebates and the information required to complete the rebate application.  while waiting for rebate approval, they touched base weekly and one day after confirmation, co-ordinated electrical and hvac companies (from two different areas of the province) and an installation date.  the contractors showed up on-time and were professional, respectful, knowledgable and surprisingly young.  by mid afternoon, a heat pump, and three heads had been neatly installed and working; and the oil tank removed.  from an office in toronto to the rural town of sandy cove, newfoundland; 1click and its sub-contractors made the whole experience smooth and hassel free.  kudos all round.
5                                                                                                                                                                                                                                                                                                                                                                                                        hello my name is robert from trout river nl . i am writing this to inform anyone looking for another source of heat for their home , to get ahold of 1click heating and cooling and there fantastic crew  especially adrianna transek who helped me out from day one all the way through till the very end !! if you are worried about paperwork and computer work then don’t be with her vast skills and knowledge she will make it all just a breeze 100% !!!! so don’t let that stop you . i didn’t . also a big shout out to their crew who came and did all the installation in just one day , with their professionalism and dedication all was a joy !!! i can’t recommend them enough! … i am 100% over the moon happy with my choice to have reached out to them all 👍👍👍.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    very positive experience, they were very helpful during the whole process. we are very pleased with our install , i think it will serve us well during the upcoming winter months here in corner brook  nl and i am sure the summer months will be more tolerable as our  upstairs get so hot , making sleeping very difficult. i would definitely recommend this product to anyone. angela and daniel
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          it was great experience with 1 click heating. george a. was very professional and accommodating. they always respond promptly and willing to accommodate based on my needs an priorities. i highly recommend this te. i went to shop around ; other company were around 3-5k expensive. thank you 1click and thank you george a.
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         great customer service on the phone from michael and my installer cecil as well. great company to deal with. being the middle of the summer they installed my unit in a efficient and timely manner.  highly recommended. the house is do much more livable during the summer now and i'm excited to see the savings come winter.
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              very pleased with the results and would suggest this company to anyone , are all very professional and very responsive with all my needs i am enjoying my new heating system
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 thanks so much for the amazing product and service! dylan and adrianna were incredible to deal with! we had to do virtually nothing replace our wood furnace  and get the grants!! we would highly recommend this company!  morgan simms corner brook nl
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  one click made switching from oil to a central heat pump system such a smooth transition. extremely knowledgeable and professional. highly recommend using this company!  glace bay, ns
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             sara lesniak  at 1-click was a wonderful lady to deal with many questions i needed answered, she walked me through everything and helped me get all the papers i needed . i live in little burnt bay nfld . she still called me back the time  difference didn’t matter . love our systems and happy that i did it . every one who helped with this was awesome. thank you sara and the team
13  would 110% not recommend! -first off one head was installed in the wrong spot from what we spoke about because the other spot was just more work. so it's now in a spot that doesn't even warm the rest of the basement just the laundry room. -drain hose was just placed in the laundry room sink not ran outside the way it should be. -only had it for a couple of months, the head upstairs doesn't blow heat just cold air. -outside condenser makes loud clunking noises also condenser was installed right in front of a dryer vent which causes lots of lent build up on coils of condenser. -we paid extra for parts and labor warranty only for them to make us trouble shoot it ourselves or we would have to pay extra for someone to come. -very rude on the phone and lies. -not considered that we have a newborn and another child in the house and our heating not working and power bill going through the roof because we're using space heaters, so much for saving money by switching to heat pumps. - calls us saying a tech will finally be by only for them to not show up, no text, emails or phone calls explaining why they didn't.  we could go on and on!
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dylan was very helpful and informative. made the grant process and install very straight forward.
15                                                                                                                                                                                                                                                                                                                                                                                                                i can't speak highly enough about 1 click and their exceptional team member, george. from the very start, george's professionalism and understanding stood out. he attentively listened to our needs and seamlessly incorporated our existing energy evaluation into his recommendations. thanks to his expertise, we were able to secure a fantastic product deal, and the entire process, from signing to financing, took just an hour. although there was a slight delay in our installation timeline due to unforeseen weather challenges in nova scotia, the team at 1 click kept us informed throughout. their dedication to quality service is truly commendable. i wholeheartedly give them five stars and am grateful to george for his outstanding assistance."

In [ ]:
df1.head()

                  Company Name                     Place ID          Author  \
0  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg   Glen Brothers
1  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg          Stacey
2  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg       Dee Brake
3  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg  Melanie Gillam
4  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg    Tony Parsons

   Rating  \
0     5.0
1     5.0
2     5.0
3     5.0
4     5.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Review Text  \
0                                  The guys showed up in full force! Installers and electricians ready to go. As a small business owner, I appreciate the coordination in doing such a job in a timely manner. 1st thing I noticed, was the relatively young age of the crew, which was a pleasant surprise! I know all too well how hard it is to recruit young workers these days. The crew was very knowledgeable in their field and worked together flawlessly. Adrianna and Mike at 1-click were great to deal with, and made the transition from oil to electric go very smoothly. No money up front, as a lot of people thought. If you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. If you are thinking of making the transition from oil to electric or looking for other options… give 1-click a call and speak to Mike or Adrianna!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                 Working with 1 Click to set up our ductless heat & air conditioning in our home in Nova Scotia has been seamlessly, worry free. Our rep George was very transparent and knowledgeable. He was and is always available to answer any questions or guidance. The installers are some of most respectful workers I’ve ever had in my home, their workmanship was impeccable! Extremely neat and professional. We would definitely recommend George and 1 Click based on our experience with them
2                                                       We knew we wanted a heat pump, but we didn't know what type was best. Originally, we considered a ducted unit, but in the end, we chose a multi split. We have 3 heads to best service our home. Kingsley was very patient and helpful with us and our indecisiveness.  He helped us choose the right unit for us.  The installation went smoothly.  The team was efficient and tidy. The units look great. Kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. They were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. Kingsley even helped us with the application and financing websites. I would highly recommend this service to friends. I'm now enjoying the comfort of multi zone climate control.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 It was an absolute pleasure working with this company, especially Adrianna, Dylan and George. They were available and extremely helpful every step of the way, even though I know I must have drove them crazy at times. I would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered.\nMelanie,\nPort aux Basques, NL
4  On Labour Day Weekend I filled out a basic request for a quote and by noon on the Tuesday following the long weekend Kage had reached out and not only offered a written quote but financing options for the modest amount not covered by Rebates and the information required to complete the Rebate Application.\n\nWhile waiting for Rebate Approval, they touched base weekly and one day after confirmation, co-ordinated Electrical and HVAC Companies (from two different areas of the Province) and an Installation date.  The contractors showed up on-time and were professional, respectful, knowledgable and surprisingly young.\n\nBy mid afternoon, a heat pump, and three heads had been neatly installed and working; and the oil tank removed.  From an office in Toronto to the rural town of Sandy Cove, Newfoundland; 1Click and its sub-contractors made the whole experience smooth and hassel free.  Kudos all round.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Review_Text  \

In [ ]:
print("Unique locations:", df1['locations'].explode().unique())
print("Unique skills:", df1['skills'].explode().unique())

Unique locations: [None 'Nova Scotia' 'Port aux Basques' ... 'Hilden Homes' 'Arlington'
 'Amsterdam']
Unique skills: [None 'air conditioning construction' 'basement construction' ...
 'Home Builder Kitchen Award' 'Aspenite' 'HNHomes']

In [ ]:
print("Data type in locations column:", df1['locations'].apply(type).unique())
print("Data type in skills column:", df1['skills'].apply(type).unique())

Data type in locations column: [<class 'NoneType'> <class 'list'>]
Data type in skills column: [<class 'NoneType'> <class 'list'>]

In [ ]:
# Filtering based on the preference of investors
def filter_architects(df, location=None, budget=None, skills=None):
    filtered_df = df.copy()

    if location:
        filtered_df = filtered_df[filtered_df['locations'].apply(lambda x: isinstance(x, list) and location in x)]

    if skills:
        filtered_df = filtered_df[filtered_df['skills'].apply(lambda x: isinstance(x, list) and any(skill in x for skill in skills))]

    return filtered_df

# example: filtering with specific skills (garage construction, pool construction)
filtered_architects = filter_architects(df1, location="Toronto", skills=['garage construction', 'pool construction'])

# Show the result
print(filtered_architects[['builder_names', 'companies', 'locations', 'skills']])

      builder_names  \
31800          None
31824          None
33071          None
37559          None
37687    VJ Hammond
39837        Halsey
62696          None
63649          None
64602          None
74120         Pratt

                                                                companies  \
31800                                                            [Guelph]
31824                                                            [Guelph]
33071                                                    [Tricon, Tricon]
37559  [Maytag, Whirlpool, Whirlpool Canada, Whirlpool, Whirlpool Canada]
37687                                               [Whirpool, Whirlpool]
39837                                     [FAR, Gonte Construction, ODSP]
62696                                                         [Whirlpool]
63649                                                         [Whirlpool]
64602                                                         [Whirlpool]
74120                                                [Pratt Service Team]

                                                                           locations  \
31800                                                 [Thomasfield, Guelph, Toronto]
31824                                                 [Thomasfield, Guelph, Toronto]
33071                                                    [Toronto, The Selby, Selby]
37559                                                                      [Toronto]
37687                                     [U.S., china, China, Toronto, Mississauga]
39837  [Toronto, Halsey Avenue, HILTON, East York, ON, Toronto, Halsey Ave, Toronto]
62696                                                                      [Toronto]
63649                                                                      [Toronto]
64602                                                                      [Toronto]
74120                                                       [Pratt, Barrie, Toronto]

                                             skills
31800                         [garage construction]
31824                         [garage construction]
33071  [garage construction, security construction]
37559                [Live Chat, pool construction]
37687                           [pool construction]
39837    [pool construction, elevator construction]
62696                           [pool construction]
63649                           [pool construction]
64602                           [pool construction]
74120   [garage construction, storage construction]

In [ ]:
# filtering the builders which specialize "garage construction"
garage_specialists = df1[df1['skills'].apply(lambda x: 'garage construction' in (x or []))]

# show the result
print(garage_specialists[['Company Name', 'builder_names', 'skills']])

                    Company Name builder_names  \
167           Alair Homes Barrie  Alair Barrie
179           Alair Homes Barrie         Alair
195    1st Choice Home Solutions          None
196    1st Choice Home Solutions          None
199    1st Choice Home Solutions          Reno
...                          ...           ...
95071             Highbury Doors         Chris
95073             Highbury Doors         Chris
95074             Highbury Doors         Chris
95079             Highbury Doors         Chris
95145               Holden Truss          None

                                                                                skills
167                                                              [garage construction]
179                                                              [garage construction]
195                                           [garage construction, roof construction]
196                                           [garage construction, roof construction]
199    [Summer of 2022, garage construction, basement construction, roof construction]
...                                                                                ...
95071                                                            [garage construction]
95073                                                            [garage construction]
95074                                                            [garage construction]
95079                                                            [garage construction]
95145                                                            [garage construction]

[640 rows x 3 columns]

# Flair sentiment anaysis with NER

In [ ]:
from flair.models import TextClassifier
from flair.data import Sentence


#df = pd.read_csv("/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/merged_text_based_reviews_cleaned.csv")

# load sentiment analysis model from Flair
classifier = TextClassifier.load('sentiment')

# function to apply sentiment analysis
def get_sentiment(text):
    sentence = Sentence(text)
    classifier.predict(sentence)
    sentiment_label = sentence.labels[0].value  # label with positive/negative
    sentiment_score = sentence.labels[0].score  # confident level(range 0~1）
    return sentiment_label, sentiment_score

# calculate the sentiment score and add to the dataframe
df1['sentiment'], df1['sentiment_score'] = zip(*df1['cleaned_review'].apply(get_sentiment))

# show the result
df1[['cleaned_review', 'sentiment', 'sentiment_score']].head()

2024-10-21 01:05:58,227 https://nlp.informatik.hu-berlin.de/resources/models/sentiment-curated-distilbert/sentiment-en-mix-distillbert_4.pt not found in cache, downloading to /tmp/tmp1m5ueu9d

100%|██████████| 253M/253M [00:15<00:00, 17.3MB/s]

2024-10-21 01:06:14,110 copying /tmp/tmp1m5ueu9d to cache at /root/.flair/models/sentiment-en-mix-distillbert_4.pt

2024-10-21 01:06:14,662 removing temp file /tmp/tmp1m5ueu9d

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

,cleaned_review,sentiment,sentiment_score
0,"the guys showed up in full force! installers and electricians ready to go. as a small business owner, i appreciate the coordination in doing such a job in a timely manner. 1st thing i noticed, was the relatively young age of the crew, which was a pleasant surprise! i know all too well how hard it is to recruit young workers these days. the crew was very knowledgeable in their field and worked together flawlessly. adrianna and mike at 1-click were great to deal with, and made the transition from oil to electric go very smoothly. no money up front, as a lot of people thought. if you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. if you are thinking of making the transition from oil to electric or looking for other options… give 1-click a call and speak to mike or adrianna!",POSITIVE,0.999418
1,"working with 1 click to set up our ductless heat & air conditioning in our home in nova scotia has been seamlessly, worry free. our rep george was very transparent and knowledgeable. he was and is always available to answer any questions or guidance. the installers are some of most respectful workers i’ve ever had in my home, their workmanship was impeccable! extremely neat and professional. we would definitely recommend george and 1 click based on our experience with them",POSITIVE,0.999795
2,"we knew we wanted a heat pump, but we didn't know what type was best. originally, we considered a ducted unit, but in the end, we chose a multi split. we have 3 heads to best service our home. kingsley was very patient and helpful with us and our indecisiveness. he helped us choose the right unit for us. the installation went smoothly. the team was efficient and tidy. the units look great. kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. they were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. kingsley even helped us with the application and financing websites. i would highly recommend this service to friends. i'm now enjoying the comfort of multi zone climate control.",POSITIVE,0.999838
3,"it was an absolute pleasure working with this company, especially adrianna, dylan and george. they were available and extremely helpful every step of the way, even though i know i must have drove them crazy at times. i would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered. melanie, port aux basques, nl",POSITIVE,0.998910
4,"on labour day weekend i filled out a basic request for a quote and by noon on the tuesday following the long weekend kage had reached out and not only offered a written quote but financing options for the modest amount not covered by rebates and the information required to complete the rebate application. while waiting for rebate approval, they touched base weekly and one day after confirmation, co-ordinated electrical and hvac companies (from two different areas of the province) and an installation date. the contractors showed up on-time and were professional, respectful, knowledgable and surprisingly young. by mid afternoon, a heat pump, and three heads had been neatly installed and working; and the oil tank removed. from an office in toronto to the rural town of sandy cove, newfoundland; 1click and its sub-contractors made the whole experience smooth and hassel free. kudos all round.",POSITIVE,0.999938

In [ ]:
# save the data frame as CSV
df1.to_csv('/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/flair_review_with_sentiment_with_NER.csv', index=False)

# show the result of sentiment analysis
df1[['cleaned_review', 'sentiment', 'sentiment_score']].head()

NameError: name 'df1' is not defined

In [ ]:
df1.head()

In [ ]:
# decide the threshhold. Let's say more than 0.7 is positive review.
threshold = 0.7

# extract builers which have only positive sentiment scores
positive_reviews = df1[df1['sentiment_score'] >= threshold]

# filtering with skill(positive review with the companies specialized garage construction for example)
positive_garage_specialists = positive_reviews[positive_reviews['skills'].apply(lambda x: 'garage construction' in (x or []))]

# show the result
positive_garage_specialists[['Company Name', 'builder_names', 'Review Text', 'sentiment', 'sentiment_score']].head()

In [ ]:
# calculate the average sentiment analysis score each company
builder_scores = df1.groupby('Company Name')['sentiment_score'].mean().reset_index()

# sort the score with ascending. Higher score of companies are above.
top_builders = builder_scores.sort_values(by='sentiment_score', ascending=False)

# check the order
top_builders.head(30)

# NER by Hugging Face (DistilBERT)

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/merged_text_based_reviews_cleaned.csv")

In [ ]:
from transformers import pipeline

# load the pipeline of NER from Hugging Face
ner_pipeline = pipeline('ner', model='Davlan/distilbert-base-multilingual-cased-ner-hrl', tokenizer='Davlan/distilbert-base-multilingual-cased-ner-hrl')

# excute NER
sentence = "Barack Obama was born in Hawaii."
ner_results = ner_pipeline(sentence)

# result
for entity in ner_results:
    print(f"Entity: {entity['word']}, Label: {entity['entity']}")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/876 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/270 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

Entity: Barack, Label: B-PER
Entity: Obama, Label: I-PER
Entity: Hawaii, Label: B-LOC

In [ ]:
# function for NER
def apply_ner_bert(text):
    ner_results = ner_pipeline(text)
    return ner_results

In [ ]:
# change the data type to string in Review Text column
df2['Review_Text'] = str(df2['Review Text'])

In [ ]:
# apply NER to entire dataset
df2['entities'] = df2['Review Text'].apply(apply_ner_bert)

#save the result
df2.to_csv('/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/ner_result_bert.csv', index=False)

In [ ]:
# import pandas and ast
import pandas as pd
import ast  # convert to list

df3 = pd.read_csv('/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/ner_result_bert.csv')

In [ ]:
# function to clean the reviews (eliminate unnecessary words and change the sentence.)
def clean_review_text(text):
    text = text.replace('\n', ' ').replace('\r', '')
    return text.strip()

# clean the sentences of column 'Review Text'. Apply the function of "clean_review_text".
df3['cleaned_review'] = df3['Review Text'].apply(clean_review_text)

# check the data frame
df3.head()

   Unnamed: 0                 Company Name                     Place ID  \
0           0  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg
1           1  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg
2           2  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg
3           3  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg
4           4  1 Click Heating and Cooling  ChIJ3YAdKC0tK4gR-C65HnnGxZg

           Author  Rating  \
0   Glen Brothers     5.0
1          Stacey     5.0
2       Dee Brake     5.0
3  Melanie Gillam     5.0
4    Tony Parsons     5.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Review Text  \
0                                  The guys showed up in full force! Installers and electricians ready to go. As a small business owner, I appreciate the coordination in doing such a job in a timely manner. 1st thing I noticed, was the relatively young age of the crew, which was a pleasant surprise! I know all too well how hard it is to recruit young workers these days. The crew was very knowledgeable in their field and worked together flawlessly. Adrianna and Mike at 1-click were great to deal with, and made the transition from oil to electric go very smoothly. No money up front, as a lot of people thought. If you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. If you are thinking of making the transition from oil to electric or looking for other options… give 1-click a call and speak to Mike or Adrianna!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                 Working with 1 Click to set up our ductless heat & air conditioning in our home in Nova Scotia has been seamlessly, worry free. Our rep George was very transparent and knowledgeable. He was and is always available to answer any questions or guidance. The installers are some of most respectful workers I’ve ever had in my home, their workmanship was impeccable! Extremely neat and professional. We would definitely recommend George and 1 Click based on our experience with them
2                                                       We knew we wanted a heat pump, but we didn't know what type was best. Originally, we considered a ducted unit, but in the end, we chose a multi split. We have 3 heads to best service our home. Kingsley was very patient and helpful with us and our indecisiveness.  He helped us choose the right unit for us.  The installation went smoothly.  The team was efficient and tidy. The units look great. Kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. They were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. Kingsley even helped us with the application and financing websites. I would highly recommend this service to friends. I'm now enjoying the comfort of multi zone climate control.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 It was an absolute pleasure working with this company, especially Adrianna, Dylan and George. They were available and extremely helpful every step of the way, even though I know I must have drove them crazy at times. I would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered.\nMelanie,\nPort aux Basques, NL
4  On Labour Day Weekend I filled out a basic request for a quote and by noon on the Tuesday following the long weekend Kage had reached out and not only offered a written quote but financing options for the modest amount not covered by Rebates and the information required to complete the Rebate Application.\n\nWhile waiting for Rebate Approval, they touched base weekly and one day after confirmation, co-ordinated Electrical and HVAC Companies (from two different areas of the Province) and an Installation date.  The contractors showed up on-time and were professional, respectful, knowledgable and surprisingly young.\n\nBy mid afternoon, a heat pump, and three heads had been neatly installed and working; and the oil tank removed.  From an office in Toronto to the rural town of Sandy Cove, Newfoundland; 1Click and its sub-contractors made the whole experience smooth and hassel free.  Kudos all round.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Review_Text  \

In [ ]:
#convert str to list in the column of entities
df3['entities'] = df3['entities'].apply(lambda x: ast.literal_eval(x))

In [ ]:
# function for extracting builder name
def extract_buildername(entities):
    for entity in entities:
        if 'labels' in entity and entity['labels'][0]['value'] == 'PER':
            return entity['text']
    return None

In [ ]:
# function for extracting builder company
def extract_company(entities):
    companies = [entity['text'] for entity in entities if 'labels' in entity and entity['labels'][0]['value'] == 'ORG']
    return companies if companies else None

In [ ]:
# function for extracting builder location
def extract_location(entities):
    locations = [entity['text'] for entity in entities if 'labels' in entity and entity['labels'][0]['value'] == 'LOC']
    return locations if locations else None

In [ ]:
# function for extracting builder skills and characteristics
def extract_skills(entities, review_text):
    # extract the keyword of the specific characteristics
    skills = []
    for entity in entities:
        if 'labels' in entity and entity['labels'][0]['value'] == 'MISC':
            skills.append(entity['text'])

    # extract the specific keyword from review_text
    if "three-story" in review_text.lower():
        skills.append("three-story building")
    if "two-story" in review_text.lower():
        skills.append("two-story building")
    if "one-story" in review_text.lower():
        skills.append("one-story building")
    if "garage" in review_text.lower():
        skills.append("garage construction")
    if "basement" in review_text.lower():
        skills.append("basement construction")
    if "pool" in review_text.lower():
        skills.append("pool construction")
    if "garden" in review_text.lower():
        skills.append("garden construction")
    if "roof" in review_text.lower():
        skills.append("roof construction")
    if "elevator" in review_text.lower():
        skills.append("elevator construction")
    if "fireplace" in review_text.lower():
        skills.append("fireplace construction")
    if "security" in review_text.lower():
        skills.append("security construction")
    if "laundry" in review_text.lower():
        skills.append("laundry construction")
    if "storage" in review_text.lower():
        skills.append("storage construction")
    if "heating" in review_text.lower():
        skills.append("heating construction")
    if "cooling" in review_text.lower():
        skills.append("cooling construction")
    if "air conditioning" in review_text.lower():
        skills.append("air conditioning construction")
    if "water heater" in review_text.lower():
        skills.append("water heater construction")
    if "solar panel" in review_text.lower():
        skills.append("solar panel construction")
    if "panoramic view" in review_text.lower():
        skills.append("panoramic view construction")
    if "outdoor space" in review_text.lower():
        skills.append("outdoor space construction")
    if "balcony" in review_text.lower():
        skills.append("balcony construction")
    if "designable" in review_text.lower():
        skills.append("designable construction")
    if "interior design" in review_text.lower():
        skills.append("interior design construction")
    if "exterior design" in review_text.lower():
        skills.append("exterior design construction")
    if "renovation" in review_text.lower():
        skills.append("renovation construction")
    if "simple" in review_text.lower():
        skills.append("simple construction")
    if "sustainable" in review_text.lower():
        skills.append("sustainable construction")
    if "durable" in review_text.lower():
        skills.append("durable construction")

    return skills if skills else None

In [ ]:
# add each columns with new data
df3['builder_names'] = df3['entities'].apply(extract_buildername)
df3['companies'] = df3['entities'].apply(extract_company)
df3['locations'] = df3['entities'].apply(extract_location)
df3['skills'] = df3.apply(lambda row: extract_skills(row['entities'], row['cleaned_review']), axis=1)

# show the result
print(df3[['cleaned_review', 'builder_names', 'companies', 'locations', 'skills']].head(30))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cleaned_review  \
0                                                                                                                                                                                                                                                                              The guys showed up in full force! Installers and electricians ready to go. As a small business owner, I appreciate the coordination in doing such a job in a timely manner. 1st thing I noticed, was the relatively young age of the crew, which was a pleasant surprise! I know all too well how hard it is to recruit young workers these days. The crew was very knowledgeable in their field and worked together flawlessly. Adrianna and Mike at 1-click were great to deal with, and made the transition from oil to electric go very smoothly. No money up front, as a lot of people thought. If you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. If you are thinking of making the transition from oil to electric or looking for other options… give 1-click a call and speak to Mike or Adrianna!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Working with 1 Click to set up our ductless heat & air conditioning in our home in Nova Scotia has been seamlessly, worry free. Our rep George was very transparent and knowledgeable. He was and is always available to answer any questions or guidance. The installers are some of most respectful workers I’ve ever had in my home, their workmanship was impeccable! Extremely neat and professional. We would definitely recommend George and 1 Click based on our experience with them
2                                                                                                                                                                                                                                                                                                   We knew we wanted a heat pump, but we didn't know what type was best. Originally, we considered a ducted unit, but in the end, we chose a multi split. We have 3 heads to best service our home. Kingsley was very patient and helpful with us and our indecisiveness.  He helped us choose the right unit for us.  The installation went smoothly.  The team was efficient and tidy. The units look great. Kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. They were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. Kingsley even helped us with the application and financing websites. I would highly recommend this service to friends. I'm now enjoying the comfort of multi zone climate control.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               It was an absolute pleasure working with this company, especially Adrianna, Dylan and George. They were available and extremely helpful every step of the way, even though I know I must have drove them crazy at times. I would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered. Melanie, Port aux Basques, NL
4                                                                                                                                                                                                                                                  On Labour Day Weekend I filled out a basic request for a quote and by noon on the Tuesday following the long weekend Kage had reached out and not only offered a written quote but financing options for the modest amount not covered by Rebates and the information required to complete the Rebate Application.  While waiting for Rebate Approval, they touched base weekly and one day after confirmation, co-ordinated Electrical and HVAC Companies (from two different areas of the Province) and an Installation date.  The contractors showed up on-time and were professional, respectful, knowledgable and surprisingly young.  By mid afternoon, a heat pump, and three heads had been neatly installed and working; and the oil tank removed.  From an office in Toronto to the rural town of Sandy Cove, Newfoundland; 1Click and its sub-contractors made the whole experience smooth and hassel free.  Kudos all round.
5                                                                                                                                                                                                                                                                                                                                                                                                        Hello my name is Robert from Trout River NL . I am writing this to inform anyone looking for another source of heat for their home , to get ahold of 1click Heating and cooling and there fantastic crew  especially Adrianna Transek who helped me out from day one all the way through till the very end !! If you are worried about paperwork and computer work then don’t be with her vast skills and knowledge she will make it all just a breeze 100% !!!! So don’t let that stop you . I didn’t . Also a big shout out to their crew who came and did all the installation in just one day , with their professionalism and dedication all was a joy !!! I can’t recommend them enough! … I am 100% over the moon happy with my choice to have reached out to them all 👍👍👍.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Very positive experience, they were very helpful during the whole process. We are very pleased with our install , I think it will serve us well during the upcoming winter months here in Corner Brook  NL and I am sure the summer months will be more tolerable as our  upstairs get so hot , making sleeping very difficult. I would definitely recommend this product to anyone. Angela and Daniel
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          It was great experience with 1 click heating. George A. was very professional and accommodating. They always respond promptly and willing to accommodate based on my needs an priorities. I highly recommend this te. I went to shop around ; other company were around 3-5k expensive. Thank you 1click and Thank you George A.
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Great customer service on the phone from Michael and my installer Cecil as well. Great company to deal with. Being the middle of the summer they installed my unit in a efficient and timely manner.  Highly recommended. The house is do much more livable during the summer now and I'm excited to see the savings come winter.
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Very pleased with the results and would suggest this company to anyone , are all very professional and very responsive with all my needs I am enjoying my new heating system
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Thanks so much for the amazing product and service! Dylan and Adrianna were incredible to deal with! We had to do virtually nothing replace our wood furnace  and get the grants!! We would highly recommend this company!  Morgan Simms Corner Brook Nl
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  One click made switching from oil to a central heat pump system such a smooth transition. Extremely knowledgeable and professional. Highly recommend using this company!  Glace Bay, NS
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Sara lesniak  at 1-Click was a wonderful lady to deal with many questions I needed answered, she walked me through everything and helped me get all the papers I needed . I live In little burnt bay nfld . She still called me back the time  difference didn’t matter . Love our systems and happy that I did it . Every one who helped with this was awesome. Thank you Sara and the team
13  WOULD 110% NOT RECOMMEND! -First off one head was installed in the wrong spot from what we spoke about because the other spot was just more work. So it's now in a spot that doesn't even warm the rest of the basement just the laundry room. -drain hose was just placed in the laundry room sink not ran outside the way it should be. -only had it for a couple of months, the head upstairs doesn't blow heat just cold air. -outside condenser makes loud clunking noises also condenser was installed right In front of a dryer vent which causes lots of lent build up on coils of condenser. -We paid extra for parts and labor warranty only for them to make us trouble shoot it ourselves or we would have to pay extra for someone to come. -very rude on the phone and lies. -not considered that we have a newborn and another child in the house and our heating not working and power bill going through the roof because we're using space heaters, so much for saving money by switching to heat pumps. - calls us saying a tech will FINALLY be by only for them to not show up, no text, emails or phone Calls explaining why they didn't.  We could go on and on!
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Dylan was very helpful and informative. Made the grant process and install very straight forward.
15                                                                                                                                                                                                                                                                                                                                                                                                                I can't speak highly enough about 1 Click and their exceptional team member, George. From the very start, George's professionalism and understanding stood out. He attentively listened to our needs and seamlessly incorporated our existing energy evaluation into his recommendations. Thanks to his expertise, we were able to secure a fantastic product deal, and the entire process, from signing to financing, took just an hour. Although there was a slight delay in our installation timeline due to unforeseen weather challenges in Nova Scotia, the team at 1 Click kept us informed throughout. Their dedication to quality service is truly commendable. I wholeheartedly give them five stars and am grateful to George for his outstanding assistance."

In [ ]:
# filtering the builders which specialize "garage construction"
garage_specialists = df3[df3['skills'].apply(lambda x: 'garage construction' in (x or []))]

# show the result
print(garage_specialists[['Company Name', 'builder_names', 'skills']])

                    Company Name builder_names  \
167           Alair Homes Barrie          None
179           Alair Homes Barrie          None
195    1st Choice Home Solutions          None
196    1st Choice Home Solutions          None
199    1st Choice Home Solutions          None
...                          ...           ...
95071             Highbury Doors          None
95073             Highbury Doors          None
95074             Highbury Doors          None
95079             Highbury Doors          None
95145               Holden Truss          None

                                                                skills
167                                              [garage construction]
179                                              [garage construction]
195                           [garage construction, roof construction]
196                           [garage construction, roof construction]
199    [garage construction, basement construction, roof construction]
...                                                                ...
95071                                            [garage construction]
95073                                            [garage construction]
95074                                            [garage construction]
95079                                            [garage construction]
95145                                            [garage construction]

[640 rows x 3 columns]

#Hugging Face verison (DistilBERT) of sentiment analysis with NER

In [ ]:
!pip install transformers torch

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.46.2)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.6)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.8.30)

In [ ]:
#df2 = pd.read_csv('/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/ner_result_bert.csv')

In [ ]:
from transformers import pipeline, AutoTokenizer

# load the pipeline of sentiment analysis for Hugging Face
sentiment_pipeline = pipeline('sentiment-analysis')

# load tokenizer and restrict the token up to 512
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased", model_max_length=512, truncation=True)

# function for triming the text to 512 token
def truncate_text(text, max_tokens=512):
    tokens = tokenizer(text, truncation=True, max_length=max_tokens, return_tensors="pt")
    return tokenizer.decode(tokens["input_ids"][0], skip_special_tokens=True)

# implement sentiment analysis with triming texts
df3['Review Text'] = df3['Review Text'].apply(truncate_text)
df3['huggingface_sentiment'] = df3['Review Text'].apply(lambda x: sentiment_pipeline(x)[0]['label'])
df3['huggingface_score'] = df3['Review Text'].apply(lambda x: sentiment_pipeline(x)[0]['score'])

# show the result
df3[['Review Text', 'huggingface_sentiment', 'huggingface_score']].head()

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

,Review Text,huggingface_sentiment,huggingface_score
0,"the guys showed up in full force! installers and electricians ready to go. as a small business owner, i appreciate the coordination in doing such a job in a timely manner. 1st thing i noticed, was the relatively young age of the crew, which was a pleasant surprise! i know all too well how hard it is to recruit young workers these days. the crew was very knowledgeable in their field and worked together flawlessly. adrianna and mike at 1 - click were great to deal with, and made the transition from oil to electric go very smoothly. no money up front, as a lot of people thought. if you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. if you are thinking of making the transition from oil to electric or looking for other options … give 1 - click a call and speak to mike or adrianna!",POSITIVE,0.999284
1,"working with 1 click to set up our ductless heat & air conditioning in our home in nova scotia has been seamlessly, worry free. our rep george was very transparent and knowledgeable. he was and is always available to answer any questions or guidance. the installers are some of most respectful workers i ’ ve ever had in my home, their workmanship was impeccable! extremely neat and professional. we would definitely recommend george and 1 click based on our experience with them",POSITIVE,0.999418
2,"we knew we wanted a heat pump, but we didn ' t know what type was best. originally, we considered a ducted unit, but in the end, we chose a multi split. we have 3 heads to best service our home. kingsley was very patient and helpful with us and our indecisiveness. he helped us choose the right unit for us. the installation went smoothly. the team was efficient and tidy. the units look great. kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. they were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. kingsley even helped us with the application and financing websites. i would highly recommend this service to friends. i ' m now enjoying the comfort of multi zone climate control.",POSITIVE,0.999714
3,"it was an absolute pleasure working with this company, especially adrianna, dylan and george. they were available and extremely helpful every step of the way, even though i know i must have drove them crazy at times. i would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered. melanie, port aux basques, nl",POSITIVE,0.999507
4,"on labour day weekend i filled out a basic request for a quote and by noon on the tuesday following the long weekend kage had reached out and not only offered a written quote but financing options for the modest amount not covered by rebates and the information required to complete the rebate application. while waiting for rebate approval, they touched base weekly and one day after confirmation, co - ordinated electrical and hvac companies ( from two different areas of the province ) and an installation date. the contractors showed up on - time and were professional, respectful, knowledgable and surprisingly young. by mid afternoon, a heat pump, and three heads had been neatly installed and working ; and the oil tank removed. from an office in toronto to the rural town of sandy cove, newfoundland ; 1click and its sub - contractors made the whole experience smooth and hassel free. kudos all round.",POSITIVE,0.980915

In [ ]:
# save the data frame as CSV
df3.to_csv('/content/drive/MyDrive/NLP_exercise_12252023/Sharpest_minds_Khaled/RealEstate2_all/text_based_reviews/merge_file/huggingface_review_with_sentiment_with_NER.csv', index=False)

# show the result of sentiment analysis
df3[['Review Text', 'huggingface_sentiment', 'huggingface_score']].head()

,Review Text,huggingface_sentiment,huggingface_score
0,"the guys showed up in full force! installers and electricians ready to go. as a small business owner, i appreciate the coordination in doing such a job in a timely manner. 1st thing i noticed, was the relatively young age of the crew, which was a pleasant surprise! i know all too well how hard it is to recruit young workers these days. the crew was very knowledgeable in their field and worked together flawlessly. adrianna and mike at 1 - click were great to deal with, and made the transition from oil to electric go very smoothly. no money up front, as a lot of people thought. if you qualify for a government rebate, you only pay for the remaining balance, which they will finance for you if need be and at a reasonable rate. if you are thinking of making the transition from oil to electric or looking for other options … give 1 - click a call and speak to mike or adrianna!",POSITIVE,0.999284
1,"working with 1 click to set up our ductless heat & air conditioning in our home in nova scotia has been seamlessly, worry free. our rep george was very transparent and knowledgeable. he was and is always available to answer any questions or guidance. the installers are some of most respectful workers i ’ ve ever had in my home, their workmanship was impeccable! extremely neat and professional. we would definitely recommend george and 1 click based on our experience with them",POSITIVE,0.999418
2,"we knew we wanted a heat pump, but we didn ' t know what type was best. originally, we considered a ducted unit, but in the end, we chose a multi split. we have 3 heads to best service our home. kingsley was very patient and helpful with us and our indecisiveness. he helped us choose the right unit for us. the installation went smoothly. the team was efficient and tidy. the units look great. kingsley and the other members of the 1click team kept us informed of all the services and helped us with all our questions. they were very patient with us, considering we were completing other renovateds to our home and at one point, only had a small hole to access the basement. kingsley even helped us with the application and financing websites. i would highly recommend this service to friends. i ' m now enjoying the comfort of multi zone climate control.",POSITIVE,0.999714
3,"it was an absolute pleasure working with this company, especially adrianna, dylan and george. they were available and extremely helpful every step of the way, even though i know i must have drove them crazy at times. i would highly recommend 1click to anyone looking to install a heat pump and wanting to take advantage of the rebates being offered. melanie, port aux basques, nl",POSITIVE,0.999507
4,"on labour day weekend i filled out a basic request for a quote and by noon on the tuesday following the long weekend kage had reached out and not only offered a written quote but financing options for the modest amount not covered by rebates and the information required to complete the rebate application. while waiting for rebate approval, they touched base weekly and one day after confirmation, co - ordinated electrical and hvac companies ( from two different areas of the province ) and an installation date. the contractors showed up on - time and were professional, respectful, knowledgable and surprisingly young. by mid afternoon, a heat pump, and three heads had been neatly installed and working ; and the oil tank removed. from an office in toronto to the rural town of sandy cove, newfoundland ; 1click and its sub - contractors made the whole experience smooth and hassel free. kudos all round.",POSITIVE,0.980915

In [ ]:
# decide the threshhold. Let's say more than 0.7 is positive review.
threshold = 0.7

# extract builers which have only positive sentiment scores
positive_reviews = df3[df3['huggingface_score'] >= threshold]

# filtering with skill(positive review with the companies specialized garage construction for example)
positive_garage_specialists = positive_reviews[positive_reviews['skills'].apply(lambda x: 'garage construction' in (x or []))]

# show the result
positive_garage_specialists[['Company Name', 'builder_names', 'Review Text', 'huggingface_sentiment', 'huggingface_score']].head()

,Company Name,builder_names,Review Text,huggingface_sentiment,huggingface_score
167,Alair Homes Barrie,None,"we hired alair barrie to enlarge our garage doors, 3 singles to an oversized double and a single with an overall clearance of 8ft. the team was amazing, from our initial discussions with ryan to get contracts in place to working with our pm on a daily basis. jocelyn ( our pm ) was an absolute pleasure to work with, she looked after everything for us. she had put together a great team, provided us with updates throughout the project and took the care of all the details as if it was her own house being worked on. highly recommend alair and would definitely work with them again.",POSITIVE,0.999851
179,Alair Homes Barrie,None,we hired alair to design and build our garage / loft. the project went smooth and we were very happy with the project. thank you alair,POSITIVE,0.999876
195,1st Choice Home Solutions,None,"i had 1st choice home solutions install a new metal roof on my garage. they actually started the job ahead of schedule, and finished even more quickly than i expected. they were extremely professional, friendly and accommodating throughout the entire process ; from the sale to installation to billing. not only does the roof look amazing, but after being present throughout the installation process, i know this job was done right. it was a small job but they treated it just as importantly as any other. i am extremely pleased with my new roof!",POSITIVE,0.999797
196,1st Choice Home Solutions,None,"we couldn ' t be happier with the quality of their work. we had some very old worn and torn vinyl siding on a section of our house that needed replacing and we have an older detached garage with a low slope roof that was in dire need of a total roof & decking replacement and upgrade. the end results went way above our expectations and their workmanship was stellar. they provide highly detailed and itemized quotes and they explain clearly what the work will entail. on top of that, they ' re all professional and super friendly and provide excellent lines of communication so you ' re never in the dark about anything. i highly recommend them!",POSITIVE,0.999480
199,1st Choice Home Solutions,None,we hired 1st choice home solutions for a new roof. ( house / garage ). after our new metal roof was installed … we decided to upgrade our eaves on both our house / garage. then we got 3 new basements windows installed and 1 new upstairs bathroom window. we are super happy with everything!!!!!!!!!! summer of 2022 was the year of reno ’ s for us. 1 st choice home solutions made it all happen for us. highly recommend mike / christine miller london,POSITIVE,0.999726

In [ ]:
# calculate the average sentiment analysis score each company
builder_scores = df3.groupby('Company Name')['huggingface_score'].mean().reset_index()

# sort the score with ascending. Higher score of companies are above.
top_builders = builder_scores.sort_values(by='huggingface_score', ascending=False)

# check the order
top_builders.head(30)

                                             Company Name  huggingface_score
1481                                            Pureblink           0.999891
1707                                     Silver Carpentry           0.999890
990                   Kagan Shastri DeMelo Winer Park LLP           0.999889
1265                   Nelson Homes Builder & Renovations           0.999886
984                                 KHACHI DESIGN + BUILD           0.999886
1075                             Leis Murray Construction           0.999886
1923                        The New Home Specialists Inc.           0.999885
1893                                   The Biglieri Group           0.999885
26    AJD Design Group - Barrie Architectural Design Firm           0.999884
530                                        Dalerose Homes           0.999883
330                             Caliburn Engineering Inc.           0.999883
384                            Cedar Ridge at Cedar Point           0.999883
1959                         Tomas Pearce Interior Design           0.999883
1806                          Strik Baldinelli Moniz Ltd.           0.999883
1242                 Myles Burke Architectural Models Inc           0.999882
1798                              Stover Construction Inc           0.999882
1897         The Brownstones at Weston and Sheppard Ave W           0.999882
640         Eastern Restoration & Masonry Contractors Ltd           0.999882
1502                                          Qwest Homes           0.999882
1456                  Prestige Kitchen and Bath of London           0.999881
1483                                    Q4 Architects Inc           0.999881
417                                   Christal Mechanical           0.999881
2102                   Wellings Planning Consultants Inc.           0.999880
1839                                   Szasz Construction           0.999880
925                                     Hickory Homes Ltd           0.999880
1183                              Metropolitan Consulting           0.999880
1134                                         MVP Lighting           0.999880
315                                       COOLAID Studios           0.999880
1638                                     SAW Custom Homes           0.999879
261                                    Brock Builders Inc           0.999879